export interface Card {
  cmc?: number;
  colorIdentity?: string[];
  colors?: string[];
  imageName: string;
  layout: string;
  manaCost?: string;
  mciNumber?: string;
  name: string;
  pmr?: number;
  power?: string;
  subtypes?: string[];
  text: string;
  toughness?: string;
  type: string;
  types: string[];
}

export const keywordAbilities: string[] = [
  'Deathtouch',
  'Defender',
  'Double Strike',
  'Enchant',
  'Equip',
  'First Strike',
  'Flash',
  'Flying',
  'Haste',
  'Hexproof',
  'Indestructible',
  'Intimidate',
  'Landwalk',
  'Lifelink',
  'Protection',
  'Reach',
  'Shroud',
  'Trample',
  'Vigilance',
  'Banding',
  'Rampage',
  'Cumulative Upkeep',
  'Flanking',
  'Phasing',
  'Buyback',
  'Shadow',
  'Cycling',
  'Echo',
  'Horsemanship',
  'Fading',
  'Kicker',
  'Flashback',
  'Madness',
  'Fear',
  'Morph',
  'Amplify',
  'Provoke',
  'Storm',
  'Affinity',
  'Entwine',
  'Modular',
  'Sunburst',
  'Bushido',
  'Soulshift',
  'Splice',
  'Offering',
  'Ninjutsu',
  'Epic',
  'Convoke',
  'Dredge',
  'Transmute',
  'Bloodthirst',
  'Haunt',
  'Replicate',
  'Forecast',
  'Graft',
  'Recover',
  'Ripple',
  'Split Second',
  'Suspend',
  'Vanishing',
  'Absorb',
  'Aura Swap',
  'Delve',
  'Fortify',
  'Frenzy',
  'Gravestorm',
  'Poisonous',
  'Transfigure',
  'Champion',
  'Changeling',
  'Evoke',
  'Hideaway',
  'Prowl',
  'Reinforce',
  'Conspire',
  'Persist',
  'Wither',
  'Retrace',
  'Devour',
  'Exalted',
  'Unearth',
  'Cascade',
  'Annihilator',
  'Level Up',
  'Rebound',
  'Totem Armor',
  'Infect',
  'Battle Cry',
  'Living Weapon',
  'Undying',
  'Miracle',
  'Soulbond',
  'Overload',
  'Scavenge',
  'Unleash',
  'Cipher',
  'Evolve',
  'Extort',
  'Fuse',
  'Bestow',
  'Tribute',
  'Dethrone',
  'Hidden Agenda',
  'Outlast',
  'Prowess',
  'Dash',
  'Exploit',
  'Menace',
  'Renown',
  'Awaken',
  'Devoid',
  'Ingest',
  'Myriad',
  'Surge',
  'Skulk',
];
